workflows:
  android-release:
    name: Build Android Release APK and AAB
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17
      groups:
        - google_credentials
      vars:
        GRADLE_OPTS: -Dorg.gradle.jvmargs='-Xmx4096m'

    scripts:
      - name: Clean project
        script: |
          flutter clean

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build Release APK
        script: |
          flutter build apk --release --no-tree-shake-icons

      - name: Build Release AAB
        script: |
          flutter build appbundle --release --no-tree-shake-icons

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
